package jmb.pentahotest.frontend.gui.tables;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jmb.pentahotest.backend.controller.objects.Tipo;
import jmb.pentahotest.backend.model.QueryManager;

/**
 *
 * @author jmbalbas
 */
public class TiposView extends javax.swing.JDialog {

    /**
     * Creates new form TiposView
     * 
     * @param parent
     * @param modal
     * @param id
     */
    public TiposView(javax.swing.JDialog parent, boolean modal, String id) {
        super(parent, modal);
        initComponents();
        setTitle((!id.equals("")) ? "Editar Registro [Tipos]" : "Nuevo Registro [Tipos]");
        setLocationRelativeTo(null);
        
        tipo = new Tipo();
        
        // Nuevo gestor de consultas
        QueryManager queryManager = new QueryManager();
        
        // Vaciamos combo Reports
        jComboBoxReports.removeAllItems();
        
        if (!id.equals("")) {
            newReg = false;
            jButtonGrabarRegistro.setEnabled(true);
            jTextFieldId.setText(id);
            tipo.setId(Integer.valueOf(id));
            tipo = tipo.select();
            jTextFieldDescripcion.setText(tipo.getDescripcion());
            // Rellenamos combo Reports
            resultSet = queryManager.execute("select id, nombre from Reports where id = " + tipo.getReport() + ";");
            try {
                while (resultSet.next()) {
                    jComboBoxReports.addItem(String.valueOf(resultSet.getInt(1)) + "-" + resultSet.getString(2));
                }
            } catch (SQLException ex) {
                Logger.getLogger(TiposView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            newReg = true;
            jTextFieldId.setText(String.valueOf(tipo.getNextId()));
            tipo.setId(Integer.valueOf(jTextFieldId.getText()));
            // Rellenamos combo Reports
            jComboBoxReports.addItem("Seleccione report...");
            resultSet = queryManager.execute("select id, nombre from Reports order by id asc;");
            try {
                while (resultSet.next()) {
                    jComboBoxReports.addItem(String.valueOf(resultSet.getInt(1)) + "-" + resultSet.getString(2));
                }
            } catch (SQLException ex) {
                Logger.getLogger(TiposView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        // Cerramos gestor de consultas
        queryManager.statementClose();
        queryManager.connectionClose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonGrabarRegistro = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxReports = new javax.swing.JComboBox();
        jLabelObligatorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Id:");

        jTextFieldId.setEnabled(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Descripción:");

        jTextFieldDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDescripcionFocusLost(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Report:");

        jButtonGrabarRegistro.setText("Grabar registro");
        jButtonGrabarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrabarRegistroActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jComboBoxReports.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxReports.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxReportsItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGrabarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDescripcion)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxReports, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelObligatorio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxReports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelObligatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGrabarRegistro)
                    .addComponent(jButtonCancelar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGrabarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrabarRegistroActionPerformed
        if (!jTextFieldDescripcion.getText().equals("") && !jComboBoxReports.getSelectedItem().toString().equals("Seleccione report...")) {
            setCursor(new Cursor(Cursor.WAIT_CURSOR));
            tipo.setDescripcion(jTextFieldDescripcion.getText());
            String report = jComboBoxReports.getSelectedItem().toString();
            String[] idReport = report.split("-");
            tipo.setReport(Integer.valueOf(idReport[0]));
            if (newReg) {
                if (tipo.insert()) {
                    JOptionPane.showMessageDialog(this, "Registro grabado correctamente", "Tipos", 1);
                    setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    dispose();
                }
            } else {
                if (tipo.update()) {
                    JOptionPane.showMessageDialog(this, "Registro actualizado correctamente", "Tipos", 1);
                    setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    dispose();
                }
            }
        } else {
            jTextFieldDescripcion.setBackground(new Color(255, 224, 224));
            jLabelObligatorio.setIcon(new ImageIcon(getClass().getResource("/jmb/pentahotest/backend/controller/resources/icons/flecha.png")));
            JOptionPane.showMessageDialog(this, "Rellene los campos obligatorios", "Error", 0);
        }
    }//GEN-LAST:event_jButtonGrabarRegistroActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldDescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionFocusLost
        if (!jTextFieldDescripcion.getText().equals("")) jTextFieldDescripcion.setBackground(Color.white);
    }//GEN-LAST:event_jTextFieldDescripcionFocusLost

    private void jComboBoxReportsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxReportsItemStateChanged
        if (jComboBoxReports.getSelectedItem() != null) {
            if (!jComboBoxReports.getSelectedItem().toString().equals("Seleccione report...")) jLabelObligatorio.setIcon(null);
        }
    }//GEN-LAST:event_jComboBoxReportsItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGrabarRegistro;
    private javax.swing.JComboBox jComboBoxReports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelObligatorio;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldId;
    // End of variables declaration//GEN-END:variables

    private Tipo tipo;
    private final boolean newReg;
    private ResultSet resultSet;
}
