package jmb.pentahotest.frontend.gui;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import jmb.pentahotest.backend.model.QueryManager;
import jmb.pentahotest.frontend.gui.tables.ClientesView;
import jmb.pentahotest.frontend.gui.tables.DocumentosView;
import jmb.pentahotest.frontend.gui.tables.EmpresasView;
import jmb.pentahotest.frontend.gui.tables.ReportsView;
import jmb.pentahotest.frontend.gui.tables.TiposView;

/**
 *
 * @author jmbalbas
 */
public class TableView extends javax.swing.JDialog {

    /**
     * Creates new form TableView
     * @param parent
     * @param modal
     * @param table
     * @param query
     * @param cols
     */
    public TableView(java.awt.Frame parent, boolean modal, String table, String query, Object[] cols) {
        super(parent, modal);
        initComponents();
        setTitle("Tabla " + table);
        setLocationRelativeTo(null);
        
        this.table = table;
        this.query = query;
        this.cols = cols;
        
        // Establecemos las columnas
        modeloRegistros = new DefaultTableModel(cols, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTableRegistros.setModel(modeloRegistros);
        
        // Añadimos MouseListener a la tabla para controlar la selección al hacer doble click (evento mousePressed)
        jTableRegistros.addMouseListener(new MouseListener() {
            @Override
            public void mouseExited(MouseEvent evento) {}
            
            @Override
            public void mouseClicked(MouseEvent e) {}
            
            @Override
            public void mousePressed(MouseEvent e) {
                JTable target = (JTable) e.getSource();
                if (e.getClickCount() == 2) {
                    target.setRowSelectionAllowed(true);
                    jTextFieldSeleccion.setText((String) jTableRegistros.getValueAt(jTableRegistros.rowAtPoint(e.getPoint()), 0));
                    jButtonEditarRegistro.setEnabled(true);
                } else {
                    target.setRowSelectionAllowed(false);
                }
            }
            @Override
            public void mouseReleased(MouseEvent e) {}
            @Override
            public void mouseEntered(MouseEvent e) {}
        });
        
        // Ejecutamos consulta
        execute();
    }
    
    private void execute() {
        // Vaciamos la tabla
        modeloRegistros.setRowCount(0);
        
        queryManager = new QueryManager();
        ResultSet resultSet = queryManager.execute(query);        
        String[] fila = new String[cols.length];        
        try {
            while (resultSet.next()) {
                for (int i = 0; i < cols.length; i++) {
                    fila[i] = resultSet.getString(i + 1);
                }
                modeloRegistros.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PentahoTestView.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            queryManager.statementClose();
            queryManager.connectionClose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRegistros = new javax.swing.JTable();
        jButtonNuevoRegistro = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSeleccion = new javax.swing.JTextField();
        jButtonEditarRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableRegistros.setRowHeight(20);
        jScrollPane1.setViewportView(jTableRegistros);

        jButtonNuevoRegistro.setText("Nuevo registro");
        jButtonNuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoRegistroActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Selección:");

        jTextFieldSeleccion.setEnabled(false);

        jButtonEditarRegistro.setText("Editar registro");
        jButtonEditarRegistro.setEnabled(false);
        jButtonEditarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNuevoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoRegistro)
                    .addComponent(jButtonCancelar)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarRegistro))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoRegistroActionPerformed
        switch(table) {
            case "Documentos":
                new DocumentosView(this, true, "").setVisible(true);
                execute();
                break;
                
            case "Reports":
                new ReportsView(this, true, "").setVisible(true);
                execute();
                break;
            
            case "Clientes":
                new ClientesView(this, true, "").setVisible(true);
                execute();
                break;
            
            case "Empresas":
                new EmpresasView(this, true, "").setVisible(true);
                execute();
                break;
                
            case "Tipos":
                new TiposView(this, true, "").setVisible(true);
                execute();
                break;
        }
    }//GEN-LAST:event_jButtonNuevoRegistroActionPerformed

    private void jButtonEditarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarRegistroActionPerformed
        switch(table) {
            case "Documentos":
                new DocumentosView(this, true, jTextFieldSeleccion.getText()).setVisible(true);
                execute();
                break;
            
            case "Reports":
                new ReportsView(this, true, jTextFieldSeleccion.getText()).setVisible(true);
                execute();
                break;
            
            case "Clientes":
                new ClientesView(this, true, jTextFieldSeleccion.getText()).setVisible(true);
                execute();
                break;
            
            case "Empresas":
                new EmpresasView(this, true, jTextFieldSeleccion.getText()).setVisible(true);
                execute();
                break;
                
            case "Tipos":
                new TiposView(this, true, jTextFieldSeleccion.getText()).setVisible(true);
                execute();
                break;
        }
    }//GEN-LAST:event_jButtonEditarRegistroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditarRegistro;
    private javax.swing.JButton jButtonNuevoRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRegistros;
    private javax.swing.JTextField jTextFieldSeleccion;
    // End of variables declaration//GEN-END:variables

    private final String table;
    private final String query;
    private final Object[] cols;
    private final DefaultTableModel modeloRegistros;
    private QueryManager queryManager;
}
